app/flashcards/routes.py
from flask import Blueprint, render_template, redirect, url_for, flash, abort
from flask_login import current_user, login_required
from app import db
from app.forms import ChooseForm, AddFlashCardForm
from app.models import FlashCard
from app.utils import reset_and_get_topic_info, grade_card
import sqlalchemy as sa
from datetime import datetime
import random

flashcards_bp = Blueprint('flashcards', __name__, template_folder='templates/flashcards')


@flashcards_bp.route('/dashboard', methods=['POST', 'GET'])
@login_required
def dashboard():
    card_date = [card.last_seen.date() if card.last_seen else None for card in current_user.flash_cards]
    today = datetime.now().date()
    cards_today = card_date.count(today)
    cards_total = len(card_date)
    cards_percent_complete = round((cards_today / cards_total) * 100) if cards_total != 0 else 0
    cards_info = {
        'today': today,
        'cards_total': cards_total,
        'cards_today': cards_today,
        'cards_percent_complete': cards_percent_complete
    }
    revision = db.session.scalars(
        sa.select(FlashCard).where(FlashCard.ease <= 75).where(FlashCard.user_id == current_user.id)
    ).all()
    return render_template(
        'dashboard.html',
        title=f"Home {current_user.username}",
        cards_info=cards_info,
        revision=revision
    )


@flashcards_bp.route('/delete_card', methods=['POST', 'GET'])
@login_required
def delete_card():
    form = AddFlashCardForm()
    if form.delete.data != '-1':
        card = db.session.get(FlashCard, form.delete.data)
        db.session.delete(card)
        db.session.commit()
        return redirect(url_for('.flashcards'))
    return redirect(url_for('.flashcards'))


@flashcards_bp.route('/add_to_topic', methods=['POST', 'GET'])
@login_required
def add_to_topic():
    topics = reset_and_get_topic_info(current_user)
    form = AddFlashCardForm()
    if form.new.data != '-1' and not form.submit.data:
        card = db.session.get(FlashCard, form.new.data)
        card_form = AddFlashCardForm(topic=card.topic.title())
        return render_template(
            'flashcards.html',
            title='Flash Cards',
            topics=topics,
            form=card_form,
            mode='new'
        )

    if form.submit.data and form.validate_on_submit():
        new_card = FlashCard(
            topic=form.topic.data.lower().strip(),
            question=form.question.data.strip(),
            answer=form.answer.data.strip()
        )
        current_user.flash_cards.append(new_card)
        db.session.commit()
        return redirect(url_for('.flashcards'))
    return redirect(url_for('.flashcards'))


@flashcards_bp.route('/edit_card', methods=['POST', 'GET'])
@login_required
def edit_card():
    topics = reset_and_get_topic_info(current_user)
    form = AddFlashCardForm()
    if form.edit_question.data != '-1' and not form.submit_edit.data:
        card = db.session.get(FlashCard, form.edit_question.data)
        card_form = AddFlashCardForm(
            topic=card.topic.title(),
            question=card.question,
            answer=card.answer
        )
        return render_template(
            'flashcards.html',
            title='Flash Cards',
            topics=topics,
            form=card_form,
            topic_edit=card.topic,
            mode='edit'
        )

    if form.submit_edit.data and form.validate_on_submit():
        card = db.session.get(FlashCard, form.edit_question.data)
        card.topic = form.topic.data.lower().strip()
        card.question = form.question.data.strip()
        card.answer = form.answer.data.strip()
        db.session.commit()
        return redirect(url_for('.flashcards'))


@flashcards_bp.route('/topics', methods=['POST', 'GET'])
@login_required
def flashcards():
    topics = reset_and_get_topic_info(current_user)
    topics['revision'] = {
        card.id: {
            'topic': card.topic, 'question': card.question, 'answer': card.answer
        } for card in current_user.flash_cards if card.ease <= 75
    }
    revision_topics = set(info['topic'] for card_id, info in topics['revision'].items())
    for rev_topic in revision_topics:
        topics[f"revision - {rev_topic}"] = {
            card_id: {
                'topic': info['topic'], 'question': info['question'], 'answer': info['answer']
            } for card_id, info in topics['revision'].items() if info['topic'] == rev_topic
        }

    form = AddFlashCardForm()
    if form.validate_on_submit():
        topic = form.topic.data.lower().strip()
        question = form.question.data.strip()
        answer = form.answer.data.strip()
        card = FlashCard(topic=topic, question=question, answer=answer)
        current_user.flash_cards.append(card)
        db.session.commit()
        return redirect(url_for('.flashcards'))

    return render_template(
        'flashcards.html',
        title='Flash Cards',
        topics=topics,
        form=form,
        mode='normal'
    )


@flashcards_bp.route('/<path:topic>/<hashed_id>/<show>', methods=['POST', 'GET'])
@login_required
def view_topic(topic, hashed_id, show):
    if topic == 'revision':
        cards = [card for card in current_user.flash_cards if card.ease <= 75]
    elif 'revision -' in topic:
        before, sep, after = topic.partition('-')
        cards = [card for card in current_user.flash_cards if card.topic == after.strip() and card.ease <= 75]
    else:
        cards = [card for card in current_user.flash_cards if card.topic == topic]

    if not cards:
        flash('No cards exists for this topic.', 'danger')
        return redirect(url_for('.flashcards'))

    card = None
    if hashed_id != 'next':
        card_id = FlashCard.decode_hashed_id(hashed_id)
        if card_id:
            card = next((card for card in cards if card.id == card_id), None)

    if card is None:
        unseen_cards = [card for card in cards if not card.seen]
        if not unseen_cards:
            for card in cards:
                card.seen = False
            db.session.commit()
            unseen_cards = cards
        card = random.choice(unseen_cards)
        if any(card.last_seen for card in cards):
            seen_cards = sorted(cards, key=lambda card: card.last_seen or datetime.min)
            last_seen_card = seen_cards[-1] if seen_cards else None
            if len(cards) > 1:
                while last_seen_card and card.id == last_seen_card.id:
                    card = random.choice(unseen_cards)

    if not card.seen:
        card.last_seen = datetime.now()
    card.seen = True
    db.session.commit()
    complete = len(cards) - len([card for card in cards if not card.seen])

    form = ChooseForm()
    return render_template(
        'topic.html',
        title=f"{topic.title()} Flash Cards",
        topic=topic,
        hashed_id=card.hashed_id,
        show=show,
        card=card,
        total=len(cards),
        complete=complete,
        form=form
    )


@flashcards_bp.route('/flip_card/<path:topic>/<hashed_id>/<show>', methods=['POST', 'GET'])
@login_required
def flip_card(topic, hashed_id, show):
    new_show = 'answer' if show == 'question' else 'question'
    return redirect(url_for(
        '.view_topic',
        topic=topic,
        hashed_id=hashed_id,
        show=new_show
    ))


@flashcards_bp.route('/previous_card/<path:topic>/<hashed_id>/<show>', methods=['POST', 'GET'])
@login_required
def previous_card(topic, hashed_id, show):
    if topic == 'revision':
        cards = [card for card in current_user.flash_cards if card.ease <= 75]
    else:
        cards = [card for card in current_user.flash_cards if card.topic == topic]
    seen_cards = sorted([card for card in cards if card.last_seen is not None],
                        key=lambda card: card.last_seen)
    current_card_id = FlashCard.decode_hashed_id(hashed_id)

    current_index = None
    for i, card in enumerate(seen_cards):
        if card.id == current_card_id:
            current_index = i
            break
    if current_index is None:
        current_index = len(seen_cards) - 1

    prev_index = (current_index - 1) % len(seen_cards)
    prev_card = seen_cards[prev_index]
    prev_card_hashed_id = prev_card.hashed_id

    return redirect(url_for(
        '.view_topic',
        topic=topic,
        hashed_id=prev_card_hashed_id,
        show='question'
    ))


@flashcards_bp.route('/next_card/<path:topic>/<hashed_id>/<show>', methods=['POST', 'GET'])
@login_required
def next_card(topic, hashed_id, show):
    return redirect(url_for(
        '.view_topic',
        topic=topic,
        hashed_id='next',
        show='question'
    ))


@flashcards_bp.route('/card_correct/<path:topic>/<hashed_id>/<show>', methods=['POST', 'GET'])
@login_required
def card_correct(topic, hashed_id, show):
    card_id = FlashCard.decode_hashed_id(hashed_id)
    card = db.session.scalar(
        sa.select(FlashCard).where(FlashCard.id == card_id).where(FlashCard.user_id == current_user.id)
    ) or abort(404)
    grade_card(card, True)
    flash('Well done!', 'success')
    return redirect(url_for(
        '.next_card',
        topic=topic,
        hashed_id=hashed_id,
        show='question'
    ))


@flashcards_bp.route('/card_wrong/<path:topic>/<hashed_id>/<show>', methods=['POST', 'GET'])
@login_required
def card_wrong(topic, hashed_id, show):
    card_id = FlashCard.decode_hashed_id(hashed_id)
    card = db.session.scalar(
        sa.select(FlashCard).where(FlashCard.id == card_id).where(FlashCard.user_id == current_user.id)
    ) or abort(404)
    grade_card(card, False)
    flash('Better luck next time!', 'danger')
    return redirect(url_for(
        '.next_card',
        topic=topic,
        hashed_id=hashed_id,
        show='question'
    ))

app/flashcards/templates/flashcards/dashboard.html
{% extends "base.html" %}

{% block content %}
{% set total_cards = 100 %}
{% set size = 'all_cards_med' %}
<h1 class="border-bottom border-dark border-5 pb-5 mb-5">Welcome {{ current_user.username }}</h1>
<div class="border rounded p-2">
    <h2 class="bg-light text-center rounded mb-3">Flash Cards Today</h2>
    <div class="bg-light rounded mh-100 my-1 mx-2">
        {% for i in range(total_cards)|reverse %}
        {% if i < cards_info.cards_percent_complete %}
        {% set rounded = 'rounded-top' if i == total_cards - 1 else '' %}
        {% set top = 'border-top' if i == cards_info.cards_percent_complete - 1 else '' %}
        <div class="green_background {{ size }} {{ rounded }} {{ top }}"></div>
        {% else %}
        {% set rounded = 'rounded-top' if i == total_cards - 1 else '' %}
        <div class="bg-danger {{ size }} {{ rounded }}"></div>
        {% endif %}
        {% endfor %}
    </div>
    <h3 class="text-light text-center bg-dark rounded-bottom p-2">
        {{ cards_info.cards_today }} / {{ cards_info.cards_total }}
    </h3>
</div>
<div class="rounded shadow bg-light p-2 my-5">
    {% if revision %}
    <h5 class="text-danger">Here are some cards we recommend you revise</h5>
    <a class="btn btn-dark"
       href="{{ url_for('flashcards.view_topic', topic='revision', hashed_id='next', show='question') }}">
        Revision
    </a>
    {% else %}
    <h5 class="text-success">None of your cards revising</h5>
    {% endif %}
</div>
{% endblock %}

app/flashcards/templates/flashcards/flashcards.html
{% extends "base.html" %}
{% import "bootstrap_wtf.html" as wtf %}

{% block content %}
<h1 class="border-bottom border-dark border-5 pb-5 mb-5">Flash Cards</h1>
<h2>Topics</h2>
{% if topics %}
{% for topic, info in topics.items() %}
{% set collapse_id = 'editCollapse_' ~ loop.index %}
{% if topic == 'revision' %}
<h2 class="text-danger mt-5">Tailored Revision</h2>
{% endif %}
<div class="d-flex mb-2 align-items-center">
    <a class="btn btn-{{ 'danger' if 'revision' in topic else 'dark' }} me-2"
       href="{{ url_for('flashcards.view_topic', topic=topic, hashed_id='next', show='question') }}">
        {{ topic|title }}
    </a>
    {% if 'revision' not in topic %}
    <form action="{{ url_for('flashcards.add_to_topic') }}" method="POST" novalidate enctype="multipart/form-data">
        {{ form.csrf_token() }}
        {{ form.new(value=info|first) }}
        <button class="btn btn-outline-dark h-100">
            <i class="bi bi-plus-lg"></i>
        </button>
    </form>
    {% endif %}
    <button class="btn btn-outline-dark ms-2 h-100"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#{{ collapse_id }}"
            aria-expanded="false"
            aria-controls="{{ collapse_id }}">
        <i class="bi bi-list"></i>
    </button>
    {% if mode == 'edit' or mode == 'new' %}
    <a class="btn btn-outline-dark ms-2 h-100" href="{{ url_for('flashcards.flashcards') }}">
        Cancel
    </a>
    {% endif %}
</div>

<div class="collapse mb-3" id="{{ collapse_id }}">
    <div class="card card-body">
        <h3 class="mt-3">All Cards</h3>
        {% for id, content in info.items() %}
        <div class="d-flex mb-3">
            <table class="table">
                <thead>
                <tr class="table-light">
                    <th colspan="2"></th>
                </tr>
                <tr class="text-start">
                    <th>Question</th>
                    <td>{{ content.question }}</td>
                </tr>
                <tr class="text-start">
                    <th>Answer</th>
                    <td class="w-100">{{ content.answer }}</td>
                </tr>
                </thead>
            </table>
            <div class="d-flex align-items-center">
                <form class="h-75 me-2" action="{{ url_for('flashcards.edit_card') }}" method="POST" novalidate
                      enctype="multipart/form-data">
                    {{ form.csrf_token() }}
                    {{ form.edit_question(value=id) }}
                    <button class="btn btn-outline-dark h-100">
                        <i class="bi bi-pencil-square"></i>
                    </button>
                </form>
                <form class="h-75" action="{{ url_for('flashcards.delete_card') }}" method="POST" novalidate
                      enctype="multipart/form-data">
                    {{ form.csrf_token() }}
                    {{ form.delete(value=id) }}
                    <button class="btn btn-outline-dark h-100">
                        <i class="bi bi-trash3"></i>
                    </button>
                </form>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endfor %}
{% else %}
<h3 class="text-body-secondary">Add a flash cards to get started</h3>
{% endif %}

<div class="container border rounded bg-light p-3 my-5">
    <div class="d-flex align-items-center justify-content-between">
        <h2 class="m-0">Create Flash Card</h2>
        <button class="btn btn-outline-dark ms-2 h-100"
                id="toggleBtn"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#flashcardForm"
                aria-expanded="{{ 'true' if mode == 'new' or mode == 'edit' else 'false' }}"
                aria-controls="flashcardForm">
            <i class="bi bi-plus-lg icon-open"></i>
            <i class="bi bi-dash-lg icon-close"></i>
        </button>
    </div>
    <div class="collapse {{ 'show' if mode == 'new' or mode == 'edit' else '' }}" id="flashcardForm">
        <div class="card card-body mt-2">
            <form action="" method="POST" novalidate>
                {{ form.hidden_tag() }}
                {{ wtf.form_field(form.topic, False) }}
                {{ wtf.form_field(form.question, False) }}
                {{ wtf.form_field(form.answer, False) }}
                <div class="d-flex">
                    {% if mode == 'normal' or mode == 'new' %}
                    {{ wtf.form_field(form.submit, False) }}
                    {% elif mode == 'edit' %}
                    {{ wtf.form_field(form.submit_edit, False) }}
                    {% endif %}
                    {% if mode == 'new' or mode == 'edit' %}
                    <a class="btn btn-outline-dark ms-2 h-100" href="{{ url_for('flashcards.flashcards') }}">
                        Cancel
                    </a>
                    {% endif %}
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

app/flashcards/templates/flashcards/topic.html
{% extends "base.html" %}
{% import "bootstrap_wtf.html" as wtf %}

{% block content %}
<h1 class="text-center fw-bold border-bottom border-dark border-5 pb-5 my-3">{{ topic|title }}</h1>
<div class="d-flex w-100 flashcard_container">
    <form class="my-5"
          action="{{ url_for(
              'flashcards.previous_card',
              topic=topic,
              hashed_id=hashed_id,
              show=show
              ) }}"
          method="POST"
          novalidate
          enctype="multipart/form-data">
        <button class="btn btn-dark h-100">
            <i class="bi bi-caret-left"></i>
        </button>
    </form>
    <form class="fw-bold mx-1 w-100"
          action="{{ url_for(
              'flashcards.flip_card',
              topic=topic,
              hashed_id=card.hashed_id,
              show=show
              ) }}"
          method="POST"
          novalidate
          enctype="multipart/form-data">
        {{ form.csrf_token() }}
        {{ form.change(value=card.id) }}
        {% if show == 'question' %}
        <button class="btn btn-dark fw-bold w-100 h-100" type="submit">
            {{ card.question }}
        </button>
        {% else %}
        <button class="btn btn-success fw-bold w-100 h-100" type="submit">
            {{ card.answer }}
        </button>
        {% endif %}
    </form>
    <form class="my-5"
          action="{{ url_for(
              'flashcards.next_card',
              topic=topic,
              hashed_id=card.hashed_id,
              show=show
              ) }}"
          method="POST"
          novalidate
          enctype="multipart/form-data">
        <button class="btn btn-dark h-100">
            <i class="bi bi-caret-right"></i>
        </button>
    </form>
</div>
<div class="d-flex justify-content-center align-items-center border-top border-5 border-dark py-5 mt-2">
    <a class="btn btn-danger mx-5 p-4"
       href="{{ url_for(
           'flashcards.card_wrong',
           topic=topic,
           hashed_id=card.hashed_id,
           show=show
            ) }}">
        <i class="bi bi-x-lg fs-1"></i>
    </a>
    <h2 class="border-bottom border-5 border-dark text-center fw-bold px-4">
        {{ complete }} / {{ total }}
    </h2>
    <a class="btn btn-success mx-5 p-4"
       href="{{ url_for(
           'flashcards.card_correct',
           topic=topic,
           hashed_id=card.hashed_id,
           show=show
            ) }}">
        <i class="bi bi-check-lg fs-1"></i>
    </a>
</div>
{% endblock %}