app/admin/routes.py
from flask import Blueprint, render_template, redirect, url_for, flash
from app.forms import ChooseForm
from flask_login import current_user, logout_user, login_required
from app import db
from app.models import User

admin_bp = Blueprint('admin', __name__, template_folder='templates/admin')


@admin_bp.route('/', methods=['GET', 'POST'])
@login_required
def admin():
    form = ChooseForm()
    if current_user.role != 'Admin':
        flash('You do not have permission to access this page', 'danger')
        return redirect(url_for('public.landing'))

    if form.validate_on_submit():
        try:
            delete_value = int(form.delete.data) if form.delete.data else -1
            change_value = int(form.change.data) if form.change.data else -1
            admin_count = User.query.filter_by(role='Admin').count()

            if (
                    delete_value == current_user.id and admin_count > 1
                    or
                    change_value == current_user.id and admin_count > 1
            ):
                logout_user()

            if delete_value != -1:
                user = User.query.get(delete_value)
                if not user:
                    flash(f"User with ID: {delete_value} does not exist", 'danger')
                    return redirect(url_for('.admin'))
                if user.role == 'Admin':
                    if admin_count <= 1:
                        flash('Must have at least one admin', 'danger')
                        return redirect(url_for('.admin'))
                db.session.delete(user)
                db.session.commit()
                flash(f"{user.username} has been deleted successfully", 'success')
                return redirect(url_for('.admin'))
            elif change_value != -1:
                user = User.query.get(change_value)
                if not user:
                    flash(f"User with ID: {change_value} does not exist", 'danger')
                    return redirect(url_for('.admin'))
                if user.role == 'Admin':
                    if admin_count <= 1:
                        flash('Must have at least one admin', 'danger')
                        return redirect(url_for('.admin'))
                    user.role = 'Normal'
                else:
                    user.role = 'Admin'
                db.session.commit()
                flash(f"{user.username}'s role has been changed successfully", 'success')
                return redirect(url_for('.admin'))
        except Exception as e:
            flash('Error occurred while performing action', 'danger')
            print(f"Error: {e}")

    users = User.query.all()
    headers = ['ID', 'Username', 'Email', 'Role', 'Delete', 'Swap Role']
    return render_template(
        'admin.html',
        title='Admin Page',
        form=form,
        headers=headers,
        users=users
    )

app/flashcards/routes.py
from flask import Blueprint, render_template, redirect, url_for, flash, abort
from flask_login import current_user, login_required
from app import db
from app.forms import ChooseForm, AddFlashCardForm
from app.models import FlashCard
from app.utils import reset_and_get_topic_info, grade_card
import sqlalchemy as sa
from datetime import datetime
import random

flashcards_bp = Blueprint('flashcards', __name__, template_folder='templates/flashcards')


@flashcards_bp.route('/dashboard', methods=['POST', 'GET'])
@login_required
def dashboard():
    card_date = [card.last_seen.date() if card.last_seen else None for card in current_user.flash_cards]
    today = datetime.now().date()
    cards_today = card_date.count(today)
    cards_total = len(card_date)
    cards_percent_complete = round((cards_today / cards_total) * 100) if cards_total != 0 else 0
    cards_info = {
        'today': today,
        'cards_total': cards_total,
        'cards_today': cards_today,
        'cards_percent_complete': cards_percent_complete
    }
    revision = db.session.scalars(
        sa.select(FlashCard).where(FlashCard.ease <= 75).where(FlashCard.user_id == current_user.id)
    ).all()
    return render_template(
        'dashboard.html',
        title=f"Home {current_user.username}",
        cards_info=cards_info,
        revision=revision
    )


@flashcards_bp.route('/delete_card', methods=['POST', 'GET'])
@login_required
def delete_card():
    form = AddFlashCardForm()
    if form.delete.data != '-1':
        card = db.session.get(FlashCard, form.delete.data)
        db.session.delete(card)
        db.session.commit()
        return redirect(url_for('.flashcards'))
    return redirect(url_for('.flashcards'))


@flashcards_bp.route('/add_to_topic', methods=['POST', 'GET'])
@login_required
def add_to_topic():
    topics = reset_and_get_topic_info(current_user)
    form = AddFlashCardForm()
    if form.new.data != '-1' and not form.submit.data:
        card = db.session.get(FlashCard, form.new.data)
        card_form = AddFlashCardForm(topic=card.topic.title())
        return render_template(
            'flashcards.html',
            title='Flash Cards',
            topics=topics,
            form=card_form,
            mode='new'
        )

    if form.submit.data and form.validate_on_submit():
        new_card = FlashCard(
            topic=form.topic.data.lower().strip(),
            question=form.question.data.strip(),
            answer=form.answer.data.strip()
        )
        current_user.flash_cards.append(new_card)
        db.session.commit()
        return redirect(url_for('.flashcards'))
    return redirect(url_for('.flashcards'))


@flashcards_bp.route('/edit_card', methods=['POST', 'GET'])
@login_required
def edit_card():
    topics = reset_and_get_topic_info(current_user)
    form = AddFlashCardForm()
    if form.edit_question.data != '-1' and not form.submit_edit.data:
        card = db.session.get(FlashCard, form.edit_question.data)
        card_form = AddFlashCardForm(
            topic=card.topic.title(),
            question=card.question,
            answer=card.answer
        )
        return render_template(
            'flashcards.html',
            title='Flash Cards',
            topics=topics,
            form=card_form,
            topic_edit=card.topic,
            mode='edit'
        )

    if form.submit_edit.data and form.validate_on_submit():
        card = db.session.get(FlashCard, form.edit_question.data)
        card.topic = form.topic.data.lower().strip()
        card.question = form.question.data.strip()
        card.answer = form.answer.data.strip()
        db.session.commit()
        return redirect(url_for('.flashcards'))


@flashcards_bp.route('/topics', methods=['POST', 'GET'])
@login_required
def flashcards():
    topics = reset_and_get_topic_info(current_user)
    topics['revision'] = {
        card.id: {
            'topic': card.topic, 'question': card.question, 'answer': card.answer
        } for card in current_user.flash_cards if card.ease <= 75
    }
    revision_topics = set(info['topic'] for card_id, info in topics['revision'].items())
    for rev_topic in revision_topics:
        topics[f"revision - {rev_topic}"] = {
            card_id: {
                'topic': info['topic'], 'question': info['question'], 'answer': info['answer']
            } for card_id, info in topics['revision'].items() if info['topic'] == rev_topic
        }

    form = AddFlashCardForm()
    if form.validate_on_submit():
        topic = form.topic.data.lower().strip()
        question = form.question.data.strip()
        answer = form.answer.data.strip()
        card = FlashCard(topic=topic, question=question, answer=answer)
        current_user.flash_cards.append(card)
        db.session.commit()
        return redirect(url_for('.flashcards'))

    return render_template(
        'flashcards.html',
        title='Flash Cards',
        topics=topics,
        form=form,
        mode='normal'
    )


@flashcards_bp.route('/<path:topic>/<hashed_id>/<show>', methods=['POST', 'GET'])
@login_required
def view_topic(topic, hashed_id, show):
    if topic == 'revision':
        cards = [card for card in current_user.flash_cards if card.ease <= 75]
    elif 'revision -' in topic:
        before, sep, after = topic.partition('-')
        cards = [card for card in current_user.flash_cards if card.topic == after.strip() and card.ease <= 75]
    else:
        cards = [card for card in current_user.flash_cards if card.topic == topic]

    if not cards:
        flash('No cards exists for this topic.', 'danger')
        return redirect(url_for('.flashcards'))

    card = None
    if hashed_id != 'next':
        card_id = FlashCard.decode_hashed_id(hashed_id)
        if card_id:
            card = next((card for card in cards if card.id == card_id), None)

    if card is None:
        unseen_cards = [card for card in cards if not card.seen]
        if not unseen_cards:
            for card in cards:
                card.seen = False
            db.session.commit()
            unseen_cards = cards
        card = random.choice(unseen_cards)
        if any(card.last_seen for card in cards):
            seen_cards = sorted(cards, key=lambda card: card.last_seen or datetime.min)
            last_seen_card = seen_cards[-1] if seen_cards else None
            if len(cards) > 1:
                while last_seen_card and card.id == last_seen_card.id:
                    card = random.choice(unseen_cards)

    if not card.seen:
        card.last_seen = datetime.now()
    card.seen = True
    db.session.commit()
    complete = len(cards) - len([card for card in cards if not card.seen])

    form = ChooseForm()
    return render_template(
        'topic.html',
        title=f"{topic.title()} Flash Cards",
        topic=topic,
        hashed_id=card.hashed_id,
        show=show,
        card=card,
        total=len(cards),
        complete=complete,
        form=form
    )


@flashcards_bp.route('/flip_card/<path:topic>/<hashed_id>/<show>', methods=['POST', 'GET'])
@login_required
def flip_card(topic, hashed_id, show):
    new_show = 'answer' if show == 'question' else 'question'
    return redirect(url_for(
        '.view_topic',
        topic=topic,
        hashed_id=hashed_id,
        show=new_show
    ))


@flashcards_bp.route('/previous_card/<path:topic>/<hashed_id>/<show>', methods=['POST', 'GET'])
@login_required
def previous_card(topic, hashed_id, show):
    if topic == 'revision':
        cards = [card for card in current_user.flash_cards if card.ease <= 75]
    else:
        cards = [card for card in current_user.flash_cards if card.topic == topic]
    seen_cards = sorted([card for card in cards if card.last_seen is not None],
                        key=lambda card: card.last_seen)
    current_card_id = FlashCard.decode_hashed_id(hashed_id)

    current_index = None
    for i, card in enumerate(seen_cards):
        if card.id == current_card_id:
            current_index = i
            break
    if current_index is None:
        current_index = len(seen_cards) - 1

    prev_index = (current_index - 1) % len(seen_cards)
    prev_card = seen_cards[prev_index]
    prev_card_hashed_id = prev_card.hashed_id

    return redirect(url_for(
        '.view_topic',
        topic=topic,
        hashed_id=prev_card_hashed_id,
        show='question'
    ))


@flashcards_bp.route('/next_card/<path:topic>/<hashed_id>/<show>', methods=['POST', 'GET'])
@login_required
def next_card(topic, hashed_id, show):
    return redirect(url_for(
        '.view_topic',
        topic=topic,
        hashed_id='next',
        show='question'
    ))


@flashcards_bp.route('/card_correct/<path:topic>/<hashed_id>/<show>', methods=['POST', 'GET'])
@login_required
def card_correct(topic, hashed_id, show):
    card_id = FlashCard.decode_hashed_id(hashed_id)
    card = db.session.scalar(
        sa.select(FlashCard).where(FlashCard.id == card_id).where(FlashCard.user_id == current_user.id)
    ) or abort(404)
    grade_card(card, True)
    flash('Well done!', 'success')
    return redirect(url_for(
        '.next_card',
        topic=topic,
        hashed_id=hashed_id,
        show='question'
    ))


@flashcards_bp.route('/card_wrong/<path:topic>/<hashed_id>/<show>', methods=['POST', 'GET'])
@login_required
def card_wrong(topic, hashed_id, show):
    card_id = FlashCard.decode_hashed_id(hashed_id)
    card = db.session.scalar(
        sa.select(FlashCard).where(FlashCard.id == card_id).where(FlashCard.user_id == current_user.id)
    ) or abort(404)
    grade_card(card, False)
    flash('Better luck next time!', 'danger')
    return redirect(url_for(
        '.next_card',
        topic=topic,
        hashed_id=hashed_id,
        show='question'
    ))

app/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>
    <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
            crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
</head>

<body>
<nav class="navbar navbar-expand-sm green_background" data-bs-theme="dark">
    <div class="container">
        <a class="navbar-brand fw-bold letter_spacing_big"
           href="{{ url_for('public.landing') if current_user.is_anonymous else url_for('flashcards.dashboard') }}">
            mindCRAFT
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2">
                {% if current_user.is_anonymous %}
                <li class="nav-item border-start px-2">
                    <a class="nav-link" aria-current="page" href="{{ url_for('auth.register') }}">
                        Register
                    </a>
                </li>
                <li class="nav-item border-start px-2">
                    <a class="nav-link" aria-current="page" href="{{ url_for('auth.login') }}">
                        Login
                    </a>
                </li>
                {% endif %}
                {% if current_user.is_authenticated and current_user.role == 'Admin' %}
                    <li class="nav-item border-start px-2">
                        <a class="nav-link" aria-current="page" href="{{ url_for('admin.admin') }}">
                            Admin
                        </a>
                    </li>
                {% endif %}
                {% if current_user.is_authenticated %}
                <li class="nav-item border-start px-2">
                    <a class="nav-link" aria-current="page" href="{{ url_for('flashcards.flashcards') }}">
                        Flash Cards
                    </a>
                </li>
                <li class="nav-item border-start px-2">
                    <a class="nav-link" aria-current="page" href="{{ url_for('auth.settings') }}">
                        Settings
                    </a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>


<div class="container mt-3">
    {% block content %}{% endblock content %}
</div>

<div class="container my-1">
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
              <div class="alert alert-{{ category }}" role="alert">
                {{ message }}
              </div>
            {% endfor %}
        {% endif %}
    {% endwith %}
</div>

<footer class="bg-light text-center mt-auto py-1 w-100">
    <span>mindCRAFT</span>
</footer>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous">
</script>

</body>
</html>

app/templates/bootstrap_wtf.html
{% macro form_field(field, autofocus) %}
  {%- if field.type == 'BooleanField' %}
  <div class="form-check mb-3">
    {{ field(class='form-check-input') }}
    {{ field.label(class='form-check-label') }}
  </div>
  {%- elif field.type == 'RadioField' %}
    {{ field.label(class='form-label') }}
    {%- for item in field %}
    <div class="form-check{% if loop.last %} mb-3{% endif %}">
      {{ item(class='form-check-input') }}
      {{ item.label(class='form-check-label') }}
    </div>
    {%- endfor %}
  {%- elif field.type == 'SelectField' %}
    {{ field.label(class='form-label') }}
    {{ field(class='form-select mb-3') }}
  {%- elif field.type == 'TextAreaField' %}
  <div class="mb-3">
    {{ field.label(class='form-label') }}
    {% if autofocus %}
      {{ field(class='form-control' + (' is-invalid' if field.errors else ''), autofocus=True) }}
    {% else %}
      {{ field(class='form-control' + (' is-invalid' if field.errors else '')) }}
    {% endif %}
    {%- for error in field.errors %}
    <div class="invalid-feedback">{{ error }}</div>
    {%- endfor %}
  </div>
  {%- elif field.type == 'SubmitField' %}
  {{ field(class='btn btn-dark mb-2') }}
  {%- else %}
  <div class="mb-3">
    {{ field.label(class='form-label') }}
    {% if autofocus %}
      {{ field(class='form-control' + (' is-invalid' if field.errors else ''), autofocus=True) }}
    {% else %}
      {{ field(class='form-control' + (' is-invalid' if field.errors else '')) }}
    {% endif %}
    {%- for error in field.errors %}
    <div class="invalid-feedback">{{ error }}</div>
    {%- endfor %}
  </div>
  {%- endif %}
{% endmacro %}

{% macro quick_form(form, action="", method="post", id="", novalidate=False, autofocus=False) %}
<form
  {%- if action != None %} action="{{ action }}"{% endif -%}
  {%- if method %} method="{{ method }}"{% endif %}
  {%- if id %} id="{{ id }}"{% endif -%}
  {%- if novalidate %} novalidate{% endif -%}>
  {{ form.hidden_tag() }}
  {%- for field, errors in form.errors.items() %}
    {#
      ListWidget does not have an input_type attribute, so causes an exception here when checked. FieldList and RadioField
      both use ListWidget, so they have to be specifically excluded before checking for widget.input_type
    #}
    {%- if field.widget is defined and field.widget.input_type is defined and field.widget.input_type == 'hidden' %}
      {%- for error in errors %}
      <div class="invalid-feedback">{{ error }}</div>
      {%- endfor %}
    {%- endif %}

  {%- endfor %}

  {% set ns = namespace(first_field=autofocus) %}
  {%- for field in form %}
    {% if field.widget.input_type is undefined or field.widget.input_type != 'hidden' -%}
      {{ form_field(field, ns.first_field) }}
      {% set ns.first_field = false %}
    {%- endif %}
  {%- endfor %}
</form>
{% endmacro %}

app/templates/flash_cards.html
{% extends "base.html" %}
{% import "bootstrap_wtf.html" as wtf %}

{% block content %}
<h1 class="border-bottom border-dark border-5 pb-5 mb-5">Flash Cards</h1>
<h2>Topics</h2>
{% if topics %}
{% for topic, info in topics.items() %}
{% set collapse_id = 'editCollapse_' ~ loop.index %}
<div class="d-flex mb-2 align-items-center">
    <a class="btn btn-dark me-2"
       href="{{ url_for('flash_cards_by_topic', topic=topic, hashed_id='next', show='question') }}">
        {{ topic|title }}
    </a>
    <form action="{{ url_for('add_to_topic') }}" method="POST" novalidate enctype="multipart/form-data">
        {{ form.csrf_token() }}
        {{ form.new(value=info|first) }}
        <button class="btn btn-outline-dark h-100">
            <i class="bi bi-plus-lg"></i>
        </button>
    </form>
    <button class="btn btn-outline-dark ms-2 h-100" type="button"
            data-bs-toggle="collapse"
            data-bs-target="#{{ collapse_id }}"
            aria-expanded="false"
            aria-controls="{{ collapse_id }}">
        <i class="bi bi-list"></i>
    </button>
    {% if mode == 'edit' %}
    <a class="btn btn-outline-dark ms-2 h-100" href="{{ url_for('flash_cards') }}">Cancel</a>
    {% endif %}
</div>

<div class="collapse mb-3" id="{{ collapse_id }}">
    <div class="card card-body">
        <h3 class="mt-3">Choose Question to Edit</h3>
        {% for id, content in info.items() %}
        <div class="d-flex mb-3">
            <table class="table">
                <thead>
                <tr class="table-light">
                    <th colspan="2"></th>
                </tr>
                <tr class="text-start">
                    <th>Question</th>
                    <td>{{ content.question }}</td>
                </tr>
                <tr class="text-start">
                    <th>Answer</th>
                    <td class="w-100">{{ content.answer }}</td>
                </tr>
                </thead>
            </table>
            <div class="d-flex align-items-center">
                <form class="h-75 me-2" action="{{ url_for('edit_card') }}" method="POST" novalidate
                      enctype="multipart/form-data">
                    {{ form.csrf_token() }}
                    {{ form.edit_question(value=id) }}
                    <button class="btn btn-outline-dark h-100">
                        <i class="bi bi-pencil-square"></i>
                    </button>
                </form>
                <form class="h-75" action="{{ url_for('delete_card') }}" method="POST" novalidate
                      enctype="multipart/form-data">
                    {{ form.csrf_token() }}
                    {{ form.delete(value=id) }}
                    <button class="btn btn-outline-dark h-100">
                        <i class="bi bi-trash3"></i>
                    </button>
                </form>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endfor %}
{% else %}
<h3 class="text-body-secondary">Add a flash cards to get started</h3>
{% endif %}

<div class="container border rounded bg-light p-3 my-5">
    <h2>Create Flash Card</h2>
    <form action="" method="POST" novalidate>
        {{ form.hidden_tag() }}
        {{ wtf.form_field(form.topic, False) }}
        {{ wtf.form_field(form.question, False) }}
        {{ wtf.form_field(form.answer, False) }}
        <div class="d-flex">
            {% if mode == 'normal' or mode == 'new' %}
            {{ wtf.form_field(form.submit, False) }}
            {% elif mode == 'edit' %}
            {{ wtf.form_field(form.submit_edit, False) }}
            {% endif %}
            {% if mode == 'new' or mode == 'edit' %}
            <a class="btn btn-outline-dark ms-2 h-100" href="{{ url_for('flash_cards') }}">Cancel</a>
            {% endif %}
        </div>
    </form>
</div>
{% endblock %}

app/templates/flash_cards_topic.html
{% extends "base.html" %}
{% import "bootstrap_wtf.html" as wtf %}

{% block content %}
<h1 class="text-center fw-bold border-bottom border-dark border-5 pb-5 mb-2">{{ topic|title }}</h1>
<div class="d-flex w-100" style="height: 500px">
    <form class="my-5"
          action="{{ url_for(
              'previous_card',
              topic=topic,
              hashed_id=hashed_id,
              show=show
              ) }}"
          method="POST"
          novalidate
          enctype="multipart/form-data">
        <button class="btn btn-dark h-100">
            <i class="bi bi-caret-left"></i>
        </button>
    </form>
    <form class="fw-bold mx-1 w-100"
          action="{{ url_for(
              'flip_card',
              topic=topic,hashed_id=card.hashed_id,show=show
              ) }}"
          method="POST"
          novalidate
          enctype="multipart/form-data">
        {{ form.csrf_token() }}
        {{ form.change(value=card.id) }}
        {% if show == 'question' %}
        <button class="btn btn-dark fw-bold w-100 h-100" type="submit">
            {{ card.question }}
        </button>
        {% else %}
        <button class="btn btn-success fw-bold w-100 h-100" type="submit">
            {{ card.answer }}
        </button>
        {% endif %}
    </form>
    <form class="my-5"
          action="{{ url_for(
              'next_card',
              topic=topic,
              hashed_id=card.hashed_id,
              show=show
              ) }}"
          method="POST"
          novalidate
          enctype="multipart/form-data">
        <button class="btn btn-dark h-100">
            <i class="bi bi-caret-right"></i>
        </button>
    </form>
</div>
<h2 class="text-center fw-bold border-top border-dark border-5 pt-5 mt-2">
    {{ complete }} / {{ total }}
</h2>
{% endblock %}

app/templates/home.html
{% extends "base.html" %}

{% block content %}
<h1>Welcome</h1>
{% endblock %}

app/templates/settings.html
{% extends "base.html" %}
{% import "bootstrap_wtf.html" as wtf %}

{% block content %}
<h1 class="border-bottom border-dark border-5 pb-5 mb-5">Settings</h1>
<a class="btn btn-dark" href="{{ url_for('change_password') }}">Change Password</a>
<a class="btn btn-dark" href="{{ url_for('logout') }}">Logout</a>
{% endblock %}

app/templates/user_home.html
{% extends "base.html" %}

{% block content %}
{% set total_cards = 100 %}
{% set size = 'all_cards_med' %}
<h1 class="border-bottom border-dark border-5 pb-5 mb-5">Welcome {{ current_user.username }}</h1>
<div class="border rounded p-2">
    <h2 class="bg-light text-center rounded mb-3">Flash Cards Today</h2>
    <div class="bg-light rounded mh-100 my-1 mx-2">
        {% for i in range(total_cards)|reverse %}
            {% if i < cards_info.cards_percent_complete %}
                {% set rounded = 'rounded-top' if i == total_cards - 1 else '' %}
                {% set top = 'border-top' if i == cards_info.cards_percent_complete - 1 else '' %}
                <div class="green_background {{ size }} {{ rounded }} {{ top }}"></div>
            {% else %}
                {% set rounded = 'rounded-top' if i == total_cards - 1 else '' %}
                <div class="bg-danger {{ size }} {{ rounded }}"></div>
            {% endif %}
        {% endfor %}
    </div>
    <h3 class="text-light text-center bg-dark rounded-bottom p-2">
        {{ cards_info.cards_today }} / {{ cards_info.cards_total }}
    </h3>
</div>
{% endblock %}